# Default values for convoy-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  replicaCount: 1
  port: 5005
  resources:
    limits:
      cpu: 50m
      memory: 60Mi
    requests:
      cpu: 40m
      memory: 50Mi
env:
  sign_up_enabled: false
  auth:
    jwt:
      enabled: true
    native:
      enabled: true
  log_level: "error"
  environment: ""
  host: ""
  search:
    enabled: false
    type: ""
    api_key: ""
    host: ""
  tracer:
    enabled: false
    app_name: ""
    config_enabled: false
    distributed_tracer_enabled: false
    license_key: ""
    type: ""
  storage:
    enabled: false
    type: ""
    on_prem:
      path: ""
    s3:
      bucket: ""
      accessKey: ""
      secretKey: ""
      region: ""
      session_token: ""
      endpoint: ""


image:
  repository: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy
  pullPolicy: Always
  tag: v23.05.3

nameOverride: "convoy-server"
fullNameOverride: "convoy-server"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: []
  tls:
    - hosts:
        - test.com
      secretName: test-tls-secret
  hosts:
    - host: test.com
      http:
        paths:
          - path: /
            pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
