# Default values for convoy worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  replicaCount: 1
  port: 5006
  resources:
    limits:
      cpu: 500m
      memory: 600Mi
    requests:
      cpu: 400m
      memory: 500Mi

env:
  sign_up_enabled: false
  environment: ""
  proxy: ""
  log_level: "error"
  smtp:
    enabled: true
    from: ""
    password: ""
    port: 0
    provider: ""
    url: ""
    username: ""
  tracer:
    enabled: false
    app_name: ""
    config_enabled: true
    distributed_tracer_enabled: true
    license_key: ""
    type: ""
  storage:
    enabled: false
    type: ""
    on_prem:
      path: ""
    s3:
      bucket: ""
      accessKey: ""
      secretKey: ""
      region: ""
      session_token: ""
      endpoint: ""

image:
  repository: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy
  pullPolicy: Always
  tag: v23.05.3

nameOverride: "convoy-worker"
fullNameOverride: "convoy-worker"

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
